### ISSUE TITLE
Some links are not relative

### ISSUE THREAD

**Issue by RudiFueller** [E2OpenPlugins/e2openplugin-OpenWebif#554] opened 2017-01-04 11:46 UTC
First thank you for changing a lot of absolute to relative links. This really helps when setting up OpenWebif via reverse proxy.

Some links are currently still missing, I saw:

/picon/*
/images/remotes/vu_normal.png

Could you please change these as well?

**Comment by Schimmelreiter** [comment] 2017-01-04 19:21
Duplicate of #190

**Closed by Schimmelreiter** 2017-01-04 19:21 UTC
