### ISSUE TITLE
[Question] Current status of EPG in XMLTV format

### ISSUE THREAD

**Issue by rchovan** [E2OpenPlugins/e2openplugin-OpenWebif#1012] opened 2020-05-14 09:24 UTC
Hi, 
what is current status for XMLTV ? 
I saw issue #975 and merge #821, but this feature is not documented in API, and of course, does not work on my set-top-box. 

Do I miss something ? 

This is my box: 
```
"imagedistro": "openatv", 
  "mem1": "1154780 kB", 
  "mem3": "482628 kB vo\u013en\u00e9 / 1154780 kB celkom", 
  "mem2": "482628 kB", 
  "oever": "OE-Alliance 4.4", 
  "transcoding": true, 
  "fp_version": 20038, 
  "kernelver": "3.14.2", 
  "uptime": "10d 13:06", 
  "enigmaver": "2020-05-02", 
  "driverdate": "20160120", 
  "imagever": "6.4.20200502", 
  "friendlychipsetdescription": "\u010cipset (Verzia frontprocesora)", 
  "shares": [], 
  "friendlyimagedistro": "OpenATV", 
  "brand": "GI", 
  "boxtype": "xpeedlx3", 
  "machinebuild": "inihdp", 
  "lcd": 0, 
  "EX": "", 
  "webifver": "OWIF 1.3.9", 
  "grabpip": 0, 
```

**Comment by jbleyel** [comment] 2020-05-14 09:36
You need the latest openwebif and you can switch between M2U and XSPF.

https://user-images.githubusercontent.com/964927/80242109-16c43e00-8665-11ea-9cba-5894a02839cf.png

**Comment by jbleyel** [comment] 2020-05-14 09:37
Please note. This is only for channel playlists and not for EPG.

**Comment by rchovan** [comment] 2020-05-14 12:11
Do you have example of usage ? 
on request http://<ip_address>/web/epgxmltv I get response: Err500 - Processing Failed

**Comment by jbleyel** [comment] 2020-05-14 13:48
http://<ip_address>/web/epgxmltv?bRef=<Bouquet Ref>&lang=<iso language code>

**Comment by jbleyel** [comment] 2020-05-14 13:49
`
http://<ip_address>/web/epgxmltv?bRef=<bouquet ref>&lang=<iso language code>
`

**Comment by rchovan** [comment] 2020-05-14 15:43
Already tried this approach, but still I have error:

request bouquets
```
url: 
http://192.168.2.7/api/bouquets

response:
{
 "bouquets": [
  [
   "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.SkylinkSlovakRepublic.tv\" ORDER BY bouquet", 
   "Skylink Slovak Republic"
  ], 
  [
   "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.favourites.tv\" ORDER BY bouquet", 
   "Skylink CZ/SK"
  ], 
  [
   "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.iptv.tv\" ORDER BY bouquet", 
   "IPTV"
  ], 
  [
   "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.iptv_webcams.tv\" ORDER BY bouquet", 
   "IPTV Webcams"
  ], 
  [
   "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.LastScanned.tv\" ORDER BY bouquet", 
   "Last Scanned"
  ]
 ]
}
```
request epgxmltv
```
url: 
http://192.168.2.7/web/epgxmltv?bRef=%221:7:1:0:0:0:0:0:0:0:FROM%20BOUQUET%20%22userbouquet.SkylinkSlovakRepublic.tv%22%20ORDER%20BY%20bouquet%22&lang=en

response:
GET http://192.168.2.7/web/epgxmltv?bRef=%221:7:1:0:0:0:0:0:0:0:FROM%20BOUQUET%20%22userbouquet.SkylinkSlovakRepublic.tv%22%20ORDER%20BY%20bouquet%22&lang=en 500 (Internal Server Error)


```

**Comment by jbleyel** [comment] 2020-05-14 17:41
Please try this:

`http://192.168.2.7/web/epgxmltv?bRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%5C%22userbouquet.LastScanned.tv%5C%22%20ORDER%20BY%20bouquet&lang=2`

**Comment by rchovan** [comment] 2020-05-18 09:34
Hi, 
sorry for long delay. Yes, this url is working, but it is ok almost 3 min for response ? 

![image](https://user-images.githubusercontent.com/6713920/82197639-842d5c80-98fb-11ea-9c32-1fadacf205d1.png)

**Comment by jbleyel** [comment] 2020-05-18 14:11
This is not an error.
It depends on the amount of channels in your bouquet and the amount of epg entries.

**Comment by jbleyel** [comment] 2020-05-21 08:27
Can we close this issue?

You can add &endTime=XXX to limit the epg data.
XXX = max. minutes

Please do not use a value greater 10000 which means 7 days.

**Comment by rchovan** [comment] 2020-05-21 08:41
Hi, 
report is generated, but I'm not sure if it is ok, Thank for endTime, it is useful. But I think there is another error. With endTime=60 , it looks OK, 

![image](https://user-images.githubusercontent.com/6713920/82540414-4fb1de80-9b4f-11ea-98dd-c45c45980939.png)

but when I use for example 120min, then there is error:

![image](https://user-images.githubusercontent.com/6713920/82540500-73752480-9b4f-11ea-991e-ee8081f27902.png)


```
This page contains the following errors:
error on line 3473 at column 308: PCDATA invalid Char value 26
Below is a rendering of the page up to the first error.
```

**Comment by jbleyel** [comment] 2020-05-21 13:28
There is an encoding problem.

`	<desc lang="sk">The Svetlanov Symphony Orchestra of Russia and pianist Boris Berezovsky are led by conductor Vladimir Verbitsky in a performance of works by Aram Khachaturyan and Alexander Borodin. The concert was recorded in December of 2016 at the Tchaikovsky Concert Hall in Moscow and features Borodins In the Steppes of Central Asia, and Khachaturyan's Piano Concerto in D-flat Major and "Adagio from Spartacus and Phrygia" (transcription for piano and orchestra). The programme is produced by the Moscow Philharmonic Society, which Saint Petersburg-born composer Dmitri Shostakovich himself once described as playing a significant role "in the development of musical life [in Russia]. It is a kind of university which is attended by millions of music lovers and thousands of musicians." The Moscow Philharmonic Society was founded in 1922 by then-Commissar for Culture, Anatoly Lunacharsky, and has over the years come to be Russia's leading concert organizing institution.</desc>
`

I don't know how to fix because the value should be correct with this convert.

`return unicode(val, 'utf_8', errors='ignore').encode('utf_8', 'ignore')`

This can be:

A) The channel "Stingray Classica HD" sends not utf8 valid strings.
B) The epg data on your box is not full valid utf8.
C) Your image is old or have some bugs.
D) anything else

I can't fix this because i need this channel, your box and your image to reproduce this error.

**Comment by jbleyel** [comment] 2020-05-21 13:29
@ims21 : Maybe you can help here.

**Comment by jbleyel** [comment] 2020-05-21 13:55
Please put this file:

https://gist.github.com/jbleyel/abeccd1addd8f76e71a0b43586a8969b

on your Box as 

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/services.py

**Comment by rchovan** [comment] 2020-05-21 19:47
Hi, 
I think, it is working, and it is much much faster. Request without end time, which tooks almost 3 mins, took now only 650ms.

![image](https://user-images.githubusercontent.com/6713920/82598820-86b5dd80-9bab-11ea-9392-17a922b3d8c1.png)


btw, I have OpenATV 6.4, updated to latest version: 

```
  "imagedistro": "openatv", 
  "mem1": "1154780 kB", 
  "mem3": "961816 kB vo\u013en\u00e9 / 1154780 kB celkom", 
  "mem2": "961816 kB", 
  "oever": "OE-Alliance 4.4", 
  "transcoding": true, 
  "fp_version": 20038, 
  "kernelver": "3.14.2", 
  "uptime": "0:12", 
  "enigmaver": "2020-05-21", 
  "driverdate": "20160120", 
  "imagever": "6.4.20200521", 
  "friendlychipsetdescription": "\u010cipset (Verzia frontprocesora)", 
  "shares": [], 
  "timerpipzap": false, 
  "friendlyimagedistro": "OpenATV", 
  "timerautoadjust": false, 
  "brand": "GI", 
  "boxtype": "xpeedlx3", 
  "machinebuild": "inihdp", 
  "lcd": 0, 
  "EX": "", 
  "webifver": "OWIF 1.3.9", 
```

**Comment by jbleyel** [comment] 2020-05-21 20:44
I think 650 ms vs. 3 min can't be the same result.
You may have not so many epg entries after reboot and then you will have a faster result.
Please zap to  "Stingray Classica HD" and wait a few seconds.
Then zap to a few other channels and wait a few seconds.

Then try the request again.

**Comment by rchovan** [comment] 2020-05-22 09:25
You are right, 
even after EPGrefresh I have for full EPG only 137kB big response. Previously it was 400k for 2hours of EPG. I've checked it manually, for service "Stingray Classica HD (1:0:1:17D5:C91:3:EB0000:0:0:0:)"  I have only 2 results in response. Same it is for other services.  So in this changed code, request without endTime does not return all EPG entries, it is limited.

I saw this error again once, but currently I can't simulate it. When I try 1440 min for one day, it is ok, EPG for 2 days end with connection reset. 

I'll check it over weekend, because EPG for Stingray is only till Saturday. 

I have checked sRef for service, but probably it is not implemented:
```
http://192.168.2.7/web/epgxmltv?sRef=1%3A0%3A1%3A17D5%3AC91%3A3%3AEB0000%3A0%3A0%3A0%3A
```

**Comment by jbleyel** [comment] 2020-05-22 11:26
The epgxmltv is only for bouquets and not for a single service.
There are many other requests especially for services.
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/wiki/OpenWebif-API-documentation

**Comment by rchovan** [comment] 2020-05-24 07:38
Hi, 
because of some other bugs in OpenATV 6.4, I need to downgrade to OpenATV 6.3. STB was unstable, and it freezes a lot.
Anyway, I have uninstalled OpenWebIf provided with image, and installed latest version from git (https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/raw/gh-pages/enigma2-plugin-extensions-openwebif_1.3.9-e2openpluginsgit20200523_all.ipk). Then I have replaces services.pyo with file provided gist from you. 

Here is error again: 
response:
```
This page contains the following errors:
error on line 18720 at column 23: PCDATA invalid Char value 26
Below is a rendering of the page up to the first error.
```
line in xml file:
```
	<programme start="20200524220000 +0200" stop="20200525003228 +0200" channel="1:0:1:17D5:C91:3:EB0000:0:0:0:">
		<title lang="sk">Dvoák - Rusalka</title>
		<sub-title lang="sk">Dvoák - Rusalka</sub-title>
		<desc lang="sk">Ádám Fischer conducts the orchestra and choir of La Monnaie in a performance of Antonín Dvoák's (1841-1904) Rusalka, a fairytale opera in three acts. Rusalka is the composer's ninth opera and still one of the cornerstones of Czech opera houses. The main roles are played by Myrtò Papatanasiu (Rusalka), Pavel ernoch (Prince), Annalena Persson (Foreign Princess), Willard White (Vodnik) and Renée Morloc (Je¸ibaba). A rusalka is a water sprite from Slavic mythology, living in a lake or river. In this story, Rusalka wishes to become human in order to be loved by a prince. For her wish to be fulfilled, Rusalka must give up her voice and face eternal damnation if her love fails. Stage director Stefan Herheim masterfully presents this lyrical fairytale, recorded at La Monnaie, Brussels, in 2016. In this widely acclaimed interpretation, the fairytale elements sometime take on frighteningly realistic dimensions so that one might see this enchanting production as a psychoanalytical study of male fantasies and female archetypes.</desc>
	</programme>
```

and full xml response: 
[epg.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/4673102/epg.zip)

**Comment by rchovan** [comment] 2020-06-15 07:07
@jbleyel Hi, any news on this ?

**Comment by jbleyel** [comment] 2020-06-15 09:21
Hi @ims21 , can you help here? Because i have no channel with this encoding problem.

**Comment by ims21** [comment] 2020-06-15 10:15
All my EPG is broadcasted ... I think, he using imported epg ... then let solve it who creating imported EPG.

**Comment by jbleyel** [comment] 2020-06-15 10:17
Hi @ims21  : Do you have this channel?
"Stingray Classica HD (1:0:1:17D5:C91:3:EB0000:0:0:0:)"

**Comment by ims21** [comment] 2020-06-15 11:13
- Stingray Classica HD is German service => some smart boys creating EPG in M$ Word and not in some utf-8 prof. program. Lat1 has not "ř".  It is wrong converted to UTF-8 on provider side.
In utf-8 there must be "ř" as 2chars: 0xC5 0x99

I have in E2 there Dvoák instead Dvořák. I don't care.

**Comment by ims21** [comment] 2020-06-15 11:22
In CP1250 is "ř" as 0xE0 => you can see, that in epg is wrong trancoded  ... in UTF-8 it must be "0xC5 0x99". Let he call to provider :)

**Comment by rchovan** [comment] 2020-06-15 14:26
@ims21, I think, that force provider to fix this on his side is almost impossible. Could you please add any error correction to avoid this error ? Even If that wrong character will be missing, is still better than crash during request.

**Comment by jbleyel** [comment] 2020-06-15 14:33
That's what i wanna do but i need the "buggy" epg.dat for testing and the sref of the channel. I have only Astra 19,2.

**Comment by rchovan** [comment] 2020-06-15 14:40
Hi, @jbleyel 
If it helps, I'm attaching zipped epg.dat, epg.xml and error line: 
[epg.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/4780942/epg.zip)

This page contains the following errors:
error on line 23316 at column 304: PCDATA invalid Char value 26
Below is a rendering of the page up to the first error.

**Comment by jbleyel** [comment] 2020-06-15 14:41
Thanks

**Comment by jbleyel** [comment] 2020-06-15 14:42
The xml is empty.  I need only the channel name.

**Comment by rchovan** [comment] 2020-06-15 14:44
sorry, 
uploading correct XML:  [epgxmltv.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/4780983/epgxmltv.zip)

**Comment by ims21** [comment] 2020-06-15 16:30
It has no sence add any of 'correction' (workarounds) to Owif or Enigma. Enigma or Owif, both know live with it well.  I have no crash on this.

If you have crash , this crash must do your EPG imported. Solve it in this importer, that it will drop this chars...

**Comment by jbleyel** [comment] 2020-06-15 16:37
Hi @rchovan , what's the source of your EPG Data? Do you get the EPG from SAT only?

**Comment by rchovan** [comment] 2020-06-15 16:53
Yes, only from SAT, and refreshed with epgrefresh service every day.

**Comment by ims21** [comment] 2020-06-15 17:05
from sat in xml format ???

**Comment by jbleyel** [comment] 2020-06-15 17:21
No! The xml is from openwebif the epg.dat is not from an external source.
The wrong encoding comes from the sat provider.

**Comment by ims21** [comment] 2020-06-15 17:57
@jbleyel - do not add any workaround to Owif. I am using same EPG from same program with same wrong code and E2 or Owif are stable !

Let they fixing his e2...  @rchovan what EPG type do you have set in enigma ? OpenTV too ? Or some import ?

**Comment by jbleyel** [comment] 2020-06-15 18:02
I have fixed the issue but i have also fixed some other problems.
There is only a single line in owf now.
This line can be removed if e2 is fixed.

**Comment by rchovan** [comment] 2020-06-15 18:11
I'm not sure. AFAIK I have configured only epgrefresh to scan for EPG on this bouquete. And the error is not 100% reproducible, it depends on the description. As you can see in this thread, there was some days without error. 

Sorry, can't switch to english language. EPG settings:
![image](https://user-images.githubusercontent.com/6713920/84691378-53fdcb80-af44-11ea-9ee3-eccfc10e0edd.png)

**Comment by ims21** [comment] 2020-06-15 18:14
Hmm ... workaround for something, on what not crashing enigma or owif ...  Should be this optionaly? I want see, what is broadcasted.


@rchovan - try turn off any EPG and only EIT using. Then tell, if it crashing...

**Comment by ims21** [comment] 2020-06-15 18:16
Yes - whole epgcache + EPGRefresh + saving EPG is one of randomize self crashing operation ...  do not look problems, where arent. It not crashed on this chars.

**Comment by ims21** [comment] 2020-06-15 18:17
turn of saving data EPG ... why do you needed it ?

**Comment by rchovan** [comment] 2020-06-15 18:45
I have saving EPG for auto timers and restore after reboot. I have disabled saving, and other functions, deleted epg.dat and restarted E2 (init 4 > 3).
![image](https://user-images.githubusercontent.com/6713920/84694204-194a6200-af49-11ea-901f-dd9fdb6190e0.png)


```
root@xpeedlx3:~# ls  /media/hdd/epg*
ls: /media/hdd/epg*: No such file or directory
```


 After restart I have same error, even with few EPG data: 
![image](https://user-images.githubusercontent.com/6713920/84694078-dc7e6b00-af48-11ea-91bb-7dfd9e44420f.png)

**Comment by ims21** [comment] 2020-06-15 18:48
![obrazek](https://user-images.githubusercontent.com/1208763/84694478-8e1d9c00-af49-11ea-9812-d04dc95a60da.png)

**Comment by ims21** [comment] 2020-06-15 18:49
No crash ... this char is ignored.

**Comment by rchovan** [comment] 2020-06-15 18:54
@ims21  could you please generate EPG XMLTV with /web/epgxmltv service ?
I'm not talking that it is wrong displayed in browser, I'm talking, that this service can't create XMLTV file, request end with error so I can't use this service.

**Comment by ims21** [comment] 2020-06-15 19:10
XMLTV is OpenATV command or is it standard dmm command ?

**Comment by rchovan** [comment] 2020-06-15 19:13
It is OpenWebif service to generate XMLTV (http://wiki.xmltv.org/index.php/Main_Page) compatible file.
Please look at comments from this:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1012#issuecomment-628648882
to this:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1012#issuecomment-628786314

**Comment by jbleyel** [comment] 2020-06-15 19:24
Please try the latest version i have made several changes.

**Comment by rchovan** [comment] 2020-06-15 19:36
Can't build, will wait for autobuilds. I'll test it tomorrow.  Thanks.

**Comment by rchovan** [comment] 2020-06-16 05:16
can't install this new build

```
 opkg install enigma2-plugin-extensions-openwebif_1.4.0-latest_all.ipk
Upgrading enigma2-plugin-extensions-openwebif from 1.3.9-e2openpluginsgit20200523-r0 to 1.4.0-e2openpluginsgit20200615-r0 on root.
Collected errors:
 * calculate_dependencies_for: Cannot satisfy the following dependencies for enigma2-plugin-extensions-openwebif:
 *      python-six (>= 1.15) *
 * opkg_solver_install: Cannot install package enigma2-plugin-extensions-openwebif.
```

this is myversion
```
root@xpeedlx3:/hdd# opkg list-installed | grep six
python-six - 1.14.0-r0
```

**Comment by jbleyel** [comment] 2020-06-16 07:59
I will change this to 1.14.
You can use 
opkg install <ipk> --nodeps

**Comment by rchovan** [comment] 2020-06-16 09:54
Hi, reinstalled without deps. So far XMLTV is generated without error, but all description for selected provider, are in English language. I'll see how it will be with Slovak/Czech description, but probably need to wait. 

I want to check EPG manually on that channel, but realized, that I can't see EPG on any chanel in OWIF,

![image](https://user-images.githubusercontent.com/6713920/84760090-d8456280-afc7-11ea-91ab-94514e80d559.png)

**Comment by rchovan** [comment] 2020-06-17 06:10
Hi @jbleyel I can confirm, that this issue is fixed with latest version, 

OWIF 1.3:
![image](https://user-images.githubusercontent.com/6713920/84861695-ed76cb80-b071-11ea-9ab5-64a098ab8bdc.png)

OWIF 1.4:
![image](https://user-images.githubusercontent.com/6713920/84861717-f8c9f700-b071-11ea-8e47-79aeb09d4311.png)

but there is new one mentioned in previous post. Should I open new isseu for new bug ?

**Comment by jbleyel** [comment] 2020-06-17 09:12
You do not need a new issue for the epgdialog error 500 .. i need the full error.
Please enable "Debug - Display Tracebacks in browser" in openwebif settings.

**Comment by rchovan** [comment] 2020-06-17 18:44
Sorry, can't find where to enable debug. Can you navigate me or show me screenshot ?

**Comment by jbleyel** [comment] 2020-06-17 19:11
<img width="511" alt="Bildschirmfoto 2020-06-17 um 21 10 42" src="https://user-images.githubusercontent.com/964927/84939761-200add80-b0df-11ea-82c4-8dc82cc8fd00.png">

**Comment by rchovan** [comment] 2020-06-17 19:30
Here are tracebacks:

1:
```
<html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>exceptions.KeyError</span>: <span>u'\u017e'</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>197</span> in
        <span class="function">process</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">196</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">197</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">198</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>257</span> in
        <span class="function">render</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">256</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">257</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">258</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py</span>:<span>211</span> in
        <span class="function">render</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">210</span>
          <code class="code">				module = module.replace(".", "")</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">211</span>
          <code class="code">				out = self.loadTemplate(module, self.path, data)</code>
        </div><div class="snippetLine">
          <span class="lineno">212</span>
          <code class="code">				if out is None:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py</span>:<span>123</span> in
        <span class="function">loadTemplate</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">122</span>
          <code class="code">			if callable(mod):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">123</span>
          <code class="code">				return str(mod(searchList=args))</code>
        </div><div class="snippetLine">
          <span class="lineno">124</span>
          <code class="code">		elif fileExists(getViewsPath(path + ".tmpl")):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/Cheetah/Template.py</span>:<span>1005</span> in
        <span class="function">__str__</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">1004</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">1005</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">1006</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/home/oe1/atv63/build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+06efef6b30-r0/git/plugin/controllers/views/responsive/ajax/epgdialog.py</span>:<span>256</span> in
        <span class="function">respond</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">255</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">256</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">257</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/urllib.py</span>:<span>1298</span> in
        <span class="function">quote</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">1297</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">1298</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">1299</span>
          <code class="code"></code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>exceptions.KeyError</span>: <span>u'\u017e'</span>
  </div>
</div>

</body></html>

```

2:
```
<html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>exceptions.KeyError</span>: <span>u'\u0160'</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>197</span> in
        <span class="function">process</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">196</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">197</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">198</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>257</span> in
        <span class="function">render</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">256</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">257</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">258</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py</span>:<span>211</span> in
        <span class="function">render</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">210</span>
          <code class="code">				module = module.replace(".", "")</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">211</span>
          <code class="code">				out = self.loadTemplate(module, self.path, data)</code>
        </div><div class="snippetLine">
          <span class="lineno">212</span>
          <code class="code">				if out is None:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py</span>:<span>123</span> in
        <span class="function">loadTemplate</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">122</span>
          <code class="code">			if callable(mod):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">123</span>
          <code class="code">				return str(mod(searchList=args))</code>
        </div><div class="snippetLine">
          <span class="lineno">124</span>
          <code class="code">		elif fileExists(getViewsPath(path + ".tmpl")):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/Cheetah/Template.py</span>:<span>1005</span> in
        <span class="function">__str__</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">1004</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">1005</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">1006</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/home/oe1/atv63/build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+06efef6b30-r0/git/plugin/controllers/views/responsive/ajax/epgdialog.py</span>:<span>256</span> in
        <span class="function">respond</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">255</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">256</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">257</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/urllib.py</span>:<span>1298</span> in
        <span class="function">quote</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">1297</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">1298</span>
          <code class="code"></code>
        </div><div class="snippetLine">
          <span class="lineno">1299</span>
          <code class="code"></code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>exceptions.KeyError</span>: <span>u'\u0160'</span>
  </div>
</div>

</body></html>

```

**Comment by jbleyel** [comment] 2020-06-17 21:00
Please delete this file and try again.
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/epgdialog.py

**Comment by jbleyel** [comment] 2020-06-17 21:19
Please provide the epg.dat and the channel ref of one problem channel.

**Comment by jbleyel** [comment] 2020-06-18 06:38
Please get the latest version.

**Comment by rchovan** [comment] 2020-06-18 18:11
Hi, latest build fixed both of the issues. Thank You.

**Closed** 2020-06-18 18:19 UTC
