### ISSUE TITLE
Recordings do not show recording day.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#547] opened 2016-12-27 17:34 UTC
Why not?

**Comment by rklrkl** [comment] 2016-12-28 20:30
This is a duplicate of issue #541 that I raised a week ago.

**Comment by jbleyel** [comment] 2016-12-28 22:44
Please check your recordings.

<img width="439" alt="bildschirmfoto 2016-12-28 um 23 44 19" src="https://cloud.githubusercontent.com/assets/964927/21533114/9669abec-cd57-11e6-9c8a-f32ac5c87b07.png">

**Closed by jbleyel** 2016-12-28 22:44 UTC

**Comment by jbleyel** [comment] 2016-12-28 22:47
If you mean the weekday -> #541
