### ISSUE TITLE
Subbouquets

### ISSUE THREAD

**Issue by Viper-4k** [E2OpenPlugins/e2openplugin-OpenWebif#1475] opened 2022-04-11 10:39 UTC
After creating a bouquet in a bouquet, only the list of subbouquets is displayed in the openwebif, 
but not the channels in them.

The folder hierarchy is displayed correctly in the receiver's channel list.

**Comment by wedebe** [comment] 2022-04-12 06:14
Duplicate of #1463 ?

**Closed** 2022-04-12 06:53 UTC
Labels: Feature Request 💡
