### ISSUE TITLE
Memory leak in OpenWebif when accessed by VU+-Plugin from Kodi on LibreElec

### ISSUE THREAD

**Issue by PainHealer** [E2OpenPlugins/e2openplugin-OpenWebif#751] opened 2018-01-21 14:32 UTC
It seems that OpenWebif causes (or has) a memory leak when accessed by the VU+-Plugin. In this case the VU+-Plugin is installed on a LibreElec/Kodi installation on a Raspberry Pi and it accesses TV/Channel Streams, channel lists (bouquets) and EPG data. By default it does this every 2 minutes, which leads to a complete inaccessability of enigma2 after a couple of hours. 

The picture below shows how memory usage builds up continousliy. When the default value for the access of the data mentioned above is set to a higher value e.g. to 60 or 120 minutes, the memory build up is slower but in the end it will also make enigma inaccessable.
 
![openhdf_vuplus-observium](https://user-images.githubusercontent.com/35534619/35195096-9482895e-febe-11e7-9db0-a6001d26ca42.jpg)

I have tested this behavior with Kodi 16,17 and 18 builds against different openHDF (5.x,6.x) and openATV (6.x) images with the latest available openWebIf in those images (for example openHDF 6.2 with openWebif 1.28)

This behavior has also been discussed in detail here (in German language): 

https://www.vuplus-support.org/wbb4/index.php?thread/108175-ram-konsum-bis-zum-koma/&postID=1526777#post1526777

and here:

https://www.hdfreaks.cc/index.php/Thread/27245-Zugriff-auf-OpenWebif-mit-VU-Plugin-von-Kodi-killt-Gigablue/?postID=206280#post206280

Is this something that can be addressed within openWebif (configuration or developemt/bug fixing)?

**Comment by jbleyel** [comment] 2018-04-02 18:18
Please try again with the latest github version

**Comment by jbleyel** [comment] 2018-04-10 16:10
Any Update?

**Comment by jbleyel** [comment] 2018-04-10 21:32
Thanks

**Comment by jbleyel** [comment] 2018-05-09 08:55
Any update?

**Comment by jbleyel** [comment] 2018-06-22 22:01
Any update?

**Comment by PainHealer** [comment] 2018-07-01 12:39
Hello Björn,
today I found some time to test with some newer builds of the webinterface. Unfortunately I'm not a maintainer or direct contributor to any of the above mentioned E2-Images myself nor am I familiar with patching them from source (until it would only need to swap some files on the filesystem itself, but I would also need instructions which files/code have/has changed).

As stated above, today I updated from OpenHDF V6.2 #173 with OpenWebif Build 1.2.8 to OpenHDF V6.2 #221 (last/final available release in V6.2) with OpenWebif 1.3.1 and also an OpenHDF V6.3 #57 with OpenWebif 1.3.2 and I'm monitoring the memory usage right now and will report about it after testing for 24-48 hours.

Can you tell me if the OpenWebif I'm using now should have the latest changes related to the problem reported by me or if I still need to get a newer version somehow?

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-01 12:56
Hi Jens,

the latest build is only available here but some image provider like OpenATV will use this source for the nightly builds. You have to ask the image provider of OpenHDF for the source what they are using.
I think OpenHDF uses this source too for new builds. 

Regards
JB

**Comment by PainHealer** [comment] 2018-07-01 17:02
Hello Jörg,

I hoped you could tell me what version number of OpenWebif originates from the sources available here, because I'm using the latest available build of OpenHDF which is of June 26 and the version number in(side) the Webinterface available under "about" is 1.3.2. 

What I can see right now is, that the overall memory usage of OpenHDF V6.3 (and also the late V6.2 builds) is significantly lower after a reboot than before, but it is still building up with every request of the PVR-Client against the webinterface. 

![2018-07-01 19_01_01-observium](https://user-images.githubusercontent.com/35534619/42136718-33cc8bf6-7d61-11e8-88bf-ca64ca0c3653.png)

Regards

 Jens

**Comment by arn354** [comment] 2018-07-01 17:20
simply check the build-recipe of the affected distro.
openhdf uses oe-alliance. depending on image version 6.1, 6.2 branch 4.1 or 4.2 is used.

https://github.com/oe-alliance/oe-alliance-core/blob/4.1/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb

the versionnumber of openhdf should be 1.3.0 according to the bitbake recipe- at least for the packagename.

**Comment by jbleyel** [comment] 2018-07-01 17:41
Hi Jens,

i think your test using PVR-Client is not really the right way to find the leak.
You need to find all web requests of the PVR-Client via network trace.
Then send each single request in a separate way using wget/curl and find the bad one.

I can try to find the root cause if you can provide one single request with a leak result.

I have also done some tests and i can't reproduce any leak on my box.
I use the nighly build of OpenATV on Solo4K.
What tool do you use to generate the graph?

**Comment by PainHealer** [comment] 2018-07-01 17:54
Hi Jörg,

yes, I also thought about sniffing the requests, but I will have to dig a method first as I've no idea which tool I can use in this environment. I'll hopefully work something out later today.

I'm monitoring through an SNMP-Agent installed as an extension on the OpenHDF image, having "Observium" installed on Raspbian/a Raspberry Pi on the same network. Observium polls the basic system resources like RAM and CPU usage every 60 seconds (without any impact on the system itself ;-)).

**Comment by PainHealer** [comment] 2018-07-02 20:52
Hi Jörg,

I set up a new test environment today and probably found somethingm, at least I can now name some HTTP requests that definitely cause the issue.

My test environment as follows:

Gigablue HD Quad plus with OpenHDF V6.3 Build 57
Windows 10 with Kodi 17.6, Kodi with VU+-PVR-PlugIn  2.4.12, Wireshark 2.6.1 to record network traffic
Observium to do graphs over time of the consumed memory
SSH connection to the GB-Box with "top" running to monitor the memory usage permanently

I did several tests and found out that there are basically two different kinds of communication, one inital set of requests and another one that occurs frequently in the configured cycle.

The first (inital) set contains the following requests:

(all requests are like the following)
`GET /web/deviceinfo HTTP/1.1
Host: 192.168.0.13
Range: bytes=0-
User-Agent: Kodi/17.6 (Windows NT 6.1; WOW64) App_Bitness/32 Version/17.6-Git:20171114-a9a7a20
Accept: */*
Accept-Charset: UTF-8,*;q=0.8`    

(see the attached file [initial request.log](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2156730/initial.request.log) and 
[initial communication.log](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2156735/initial.communication.log) for details, the second one contains the full communication trace).

Now lets take two requests out of that set:

GET /web/timerlist HTTP/1.1

This query delivers a result set (XML response) of around 85kb of data and does not lead to more memory consumption, at least it does now get "visible", even if repeated a couple of times.

GET /web/movielist?dirname=/media/hdd/movie/The Mentalist/ HTTP/1.1

This query delivers a result set (XML) of around 330kb of data (as there are almost 750 recordings in this directory) and this one "bumps" the memory usage of the E2 process significantly (300-900kb per request) and it summs up without every getting rid of it again.

To be honest, I'm not sure if this might not be an internal issue of E2 instead of OpenWebif, because I can imagine that OpenWebif needs some additional memory each time it has to deliver such a "big" result, but why is the memory used not "released" afterwards?

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-02 21:01
Hi Jens,
please check what recordings do you have in this folder?
-> /media/hdd/movie/The Mentalist
Do you have only direct recordings of the box without changes in this folder?
No extra files (txt,cover,ect.)

--

Please create an new folder
And put only a single recoding in this folder.
Please use a recording of the box without any changes.
No extra files ect.
And then test the request with this new folder 
/web/movielist?dirname=/media/hdd/movie/<FOLDER>

Thanks.
JB

**Comment by PainHealer** [comment] 2018-07-02 21:17
Hi Jörg,

all recordings consist of the follwowing files:

![2018-07-02 23_04_56-the mentalist](https://user-images.githubusercontent.com/35534619/42186339-92158898-7e4c-11e8-8bc8-b32166b7636f.png)

That's just what E2 generates when recording/viewing the movies.

Just to make sure: There is no difference between this folder and all other folders - or the "default" recording folder /media/hdd/movie/, that contains even more recordings if not moved to sub folders -, to me it seems to be and issue of the size of the result set.

I've just tested with a single recording in one folder, no issues at all.

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-03 15:31
Hi Jens,
please test one more request.
/api/movielist?dirname=/media/hdd/movie/The Mentalist
Thanks

**Comment by PainHealer** [comment] 2018-07-05 21:06
Hi Jörg,

API-request bumps memory also, it seems to have less impact (~200-500kb per request), but takes more time, at least in a browser (5-7 seconds compared to 2-3 seconds for XML. This my be related to the browser working out the JSON result.

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-07 09:38
Here are the browser results of one folder with aprox 200 files from my box:

Full request time / download time / size
XML :  850ms / 15ms / 110KB
JSON : 610ms / 9ms / 11KB (gzip) 

The folder is not internal HDD of the box, it's NAS connected via NFS from to the box.

**Comment by PainHealer** [comment] 2018-07-11 17:24
Hi Jörg,

I guess this does not realy solve the issue, as the JSON request only saves network traffic but leads to the same memory leak while processing the request on side of the STB? It is obvious that the issue occurs on both reuqests, so changing it to JSON on side of the KODI plugin won't really help,

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-12 15:59
Hi Jens,

please test this:
Copy this file -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/movies.py
to you computer.

Edit the file at line 239
OLD : movieliste.append(movie)
NEW : #movieliste.append(movie)

Copy the file to /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models
on your box.

Then monitor the memory.
This change creates an empty xml and do any other things.

Regards
Jörg

**Comment by jbleyel** [comment] 2018-07-12 19:05
Please use this file.

[movies.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2189929/movies.py.zip)

**Comment by PainHealer** [comment] 2018-07-12 19:16
Ok,

seems I've downloaded a HTML formatted file ;-) 

With you file it works but even with the empty result memory still gets bumped with every request, doesn't matter if JSON or XML.

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-12 19:33
Next test:

[movies.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2190000/movies.py.zip)

**Comment by PainHealer** [comment] 2018-07-12 20:08
Hi Jörg,

it's the same result, memory usage is still rising when requesting the movie list for example once per minute.

Regards

 Jens

**Comment by jbleyel** [comment] 2018-07-12 21:20
The last test for today.

[movies.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2190349/movies.py.zip)

**Comment by jbleyel** [comment] 2018-07-13 22:01
Mail?

**Comment by jbleyel** [comment] 2018-08-04 10:38
Hi Jens,

any Update?

**Comment by jbleyel** [comment] 2018-09-25 11:55
UPDATE:
I have made a copy of MovieList class from here.
https://github.com/openatv/enigma2/blob/6.2/lib/python/Components/MovieList.py#L139 

-

Then i have removed all unneeded things and use this class.
-> LEAK GONE

--

**Comment by phunkyfish** [comment] 2018-11-02 23:43
I used to sometimes see this when testing on openvix.

Could a mod be needed there too?

**Comment by phunkyfish** [comment] 2020-09-24 12:55
@jbleyel I think I have a similar leak but on openvix. How would I go about removing all the unneeded things there? I'm not that skilled in python but should be able to manage with a few pointers.

**Comment by jbleyel** [comment] 2020-09-24 13:08
The memory leak is inside of the MovieList.py and not in openwebif.

**Comment by phunkyfish** [comment] 2020-09-24 13:10
Understood. But you stated above that you removed the leak by modifying the file I question and removing unneeded things.

I was curious how you did that.

**Comment by jbleyel** [comment] 2020-09-24 13:15
My modification was only a test. I don't want to make a copy of MovieList.py inside of openwebif.

**Comment by AbuBaniaz** [comment] 2020-10-03 02:28
@jbleyel 
What was the modification you made please? Where is the leak occurring so that it can be fixed properly in E2? Looks like a few images have the issue.

Thanks in advance

**Comment by jbleyel** [comment] 2020-10-03 10:27
Hi @AbuBaniaz , i have made a copy of MovieList.py from enigma2 and then i have removed all the GUI parts.
I think the leak is in the GUI part of MovieList.py.

**Comment by phunkyfish** [comment] 2020-10-04 08:16
For someone who goes understand enigma2 well how do tell which parts are the GUI parts?

**Comment by betacentauri** [comment] 2020-12-14 12:00
This fixes the problem:
https://github.com/OpenPLi/enigma2/commit/aa3956dc37132060bda553811639608d9cd96061
You can remove "del movielist" from the code.

**Comment by persianpros** [comment] 2020-12-14 13:06
@jbleyel would you please do the update?

@phunkyfish please check it after the update :+1:

**Comment by jbleyel** [comment] 2020-12-14 14:17
Hi @betacentauri, you have revert the pli change. 
Any other idea?

**Comment by betacentauri** [comment] 2020-12-14 14:58
"del movielist" don't help as Movielist was not deleted as there is a cyclic reference in the MovieList and garbage selector don't destroys the object. So removing this line is ok.

This "del movielist.list" is better and really free up memory, but still the rest of the MovieList stays in the memory. I think I have another solution. Will test it now.

**Comment by betacentauri** [comment] 2020-12-14 16:17
I hope this now fixes the problem:
https://github.com/OpenPLi/enigma2/commit/63c4e200134f185b71e7d0750ee92fc573361e57

**Comment by phunkyfish** [comment] 2020-12-14 20:46
Do I need this with the openwebif change or on it's own?

**Comment by jbleyel** [comment] 2020-12-14 22:34
You need the latest OWF and the latest OpenPLI.

**Comment by betacentauri** [comment] 2020-12-14 22:46
@phunkyfish: OpenPLi don’t build daily images. I can push it to OpenATV 6.4 tomorrow and then it needs 1-2 days until new image with the changes is build.

**Comment by phunkyfish** [comment] 2020-12-15 08:37
It’s actually OpenVix that I’m running. @AbuBaniaz can we get this fix there?

**Comment by betacentauri** [comment] 2020-12-15 08:43
It's now in ATV git. Now it needs some days until new images include it.

Which OpenVix version do you use?
AbuBaniaz has already added it to OpenVix, but I can't say when new images will be build with the patch.

**Comment by phunkyfish** [comment] 2020-12-15 09:29
I use the latest available update so it should be fairly current. @AbuBaniaz let me know if I should manually apply a patch or wait for an update when you have time.

**Comment by AbuBaniaz** [comment] 2020-12-15 14:25
The change has been added to Dev branch of OpenViX and will be in the next release image.  I don't know when the next Release of OpenViX is due.

You can get the modified file for current release branch from here:
https://raw.githubusercontent.com/AbuBaniaz/enigma2_OpenViX/phunkyfish/lib/python/Components/MovieList.py

Sorry if you know this already:
Rename the original file in /usr/lib/enigma2/python/Components  (add a .orig at end of file)
Transfer new .py file to same location
Restart, a new .pyo file will be created
Delete the .py file that you transferred

**Comment by phunkyfish** [comment] 2020-12-18 18:41
Apologies for the delay. I have the file now so you can delete the branch. Thanks, I'll report back over the next few days.

**Comment by peterurbanec** [comment] 2021-01-07 16:58
@AbuBaniaz and @betacentauri : 

I tested the _fix_ for MovieList.py, where the call to `self.l.setBuildFunc(self.buildMovieListEntry)` is relocated from `__init__` to `reload`. This change does **not** remove the memory leak, it only **reduces** the amount of memory leaked.

I measured the delta in `VmData` for the enigma2 process using a script that issued 10,000 requests:
```grep VmData /proc/$(pidof enigma2)/status ; for i in $(seq 1 100) ; do echo -n "$i " ; for j in $(seq 1 100) ; do wget http://localhost/web/movielist?dirname=/media/hdd/movie -O /dev/null -q ; done ; done; echo ; grep VmData /proc/$(pidof enigma2)/status```

The memory leaked:
Before making the `MovieList.py` change: 192544 kB leaked
After making the `MovieList.py` change: 31196 kB leaked

Clearly there is a reduction in the severity of the memory leak, but it is not eliminated.

I think this bug should be re-opened.

**Comment by phunkyfish** [comment] 2021-01-07 18:34
And I also just finished my testing today also. I can confirm that it's partially fixed. I used to get a crash every 2 days and now I get once every 2 weeks. So a considerable improvement and in line with @peterurbanec's findings.

**Comment by betacentauri** [comment] 2021-01-14 17:28
I don't have time at the moment to look at it.
@peterurbanec Can you look at it? E.g. comment out MovieList call and check whether WebIf itself has a memory leak. I think that's the case. But I don't know how big the leak is and maybe there are also other leaks.
I used objgraph to find the issue:
https://mg.pov.lt/objgraph/
https://github.com/mgedmin/objgraph/blob/master/objgraph.py
Just download the py file and import it in e.g. the WebIf code. E.g. with objgraph.show_growth() you can see what changes after x http calls.

**Comment by jbleyel** [comment] 2021-01-14 17:32
Hi @betacentauri ,

See my comment.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/751#issuecomment-424313373

**Comment by betacentauri** [comment] 2021-01-14 17:39
I think, but I have no evidences and it's too long ago ;-) that I have also removed the MovieList call and I still saw a little memory increase. But maybe I'm wrong.

**Comment by jbleyel** [comment] 2021-01-14 18:12
Please get my last commit.
Then goto movielist.py and change these 2 lines. 
OLD:
```
#from .OWFMovieList import MovieList
from Components.MovieList import MovieList

```
NEW:
```
from .OWFMovieList import MovieList
#from Components.MovieList import MovieList

```

**Comment by jbleyel** [comment] 2021-02-10 19:41
@peterurbanec , @phunkyfish  .. Any News?

**Comment by phunkyfish** [comment] 2021-02-10 20:21
@jbleyel apologies. I didn’t see your last comment. Will check this now.

**Comment by phunkyfish** [comment] 2021-02-10 21:01
I installed the latest APK but now OpenWebIfFails to start.

**Comment by jbleyel** [comment] 2021-02-10 21:08
Please uninstall and install again and provide the enigma2 debug log from the startup if OWF failed.
There must be a crash on startup.
You probably have a non 100% supported image and you get normaly the OWF from your feed.
This version on your feed is NOT the same as here.

**Comment by phunkyfish** [comment] 2021-02-10 21:21
Ok. Where do I find the Enigma2 debug log?

![Uploading 7A3287EE-E983-4D10-8DBB-B487EC6A00B0.jpeg…]()

**Comment by phunkyfish** [comment] 2021-02-10 21:22
![DC313290-E8CA-4D29-AAAA-BF40F8A18D63](https://user-images.githubusercontent.com/4601187/107573974-1b52e680-6be6-11eb-8700-aa0a16f617f2.jpeg)

**Comment by phunkyfish** [comment] 2021-02-10 21:27
Or is it that I run OpenVix and eServiceReferenceFS is not available there?

**Comment by jbleyel** [comment] 2021-02-10 21:28
Yes .. eServiceReferenceFS is only inside of the OWFMovieList.py

**Comment by phunkyfish** [comment] 2021-02-10 21:31
Ok, then let me revert the change.

**Comment by jbleyel** [comment] 2021-02-10 22:04
Please get the fixed OWFMovieList.py.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/5fd360953f988e21f1bd7276c565fb11c441c761

**Comment by phunkyfish** [comment] 2021-02-11 08:45
Ok, it’s running now. I will report back on memory usage over the next few days.

**Comment by phunkyfish** [comment] 2021-02-19 07:46
Looks promising so far:

**2020-02-11**

top - 08:45:37 up 2 min,  1 user,  load average: 1.67, 0.83, 0.32
Tasks: 109 total,   1 running, 108 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.4 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   1578.2 total,   1303.2 free,    173.1 used,    101.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1364.7 avail Mem 

**2020-02-13**

top - 09:52:31 up 2 days,  1:09,  1 user,  load average: 0.09, 0.09, 0.06
Tasks:  99 total,   1 running,  98 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   1578.2 total,   1200.4 free,    180.9 used,    196.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1352.0 avail Mem 

**2020-02-19**

top - 07:39:33 up 7 days, 22:55,  1 user,  load average: 0.00, 0.01, 0.05
Tasks:  99 total,   1 running,  98 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.1 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   1578.2 total,   1075.0 free,    194.8 used,    308.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1337.9 avail Mem 

**2020-02-11** - **2020-02-13**: 7MiB = 3.5 MiB per day
**2020-02-16** - **2020-02-19**: 14MiB = 2.3 MiB per day

Let's see what it's like by next week I imagine this would take months to leak to a crash if at all.

**Comment by phunkyfish** [comment] 2021-03-15 07:07
I restarted my device 3 weeks ago and took another **top** reading.

**2020-03-15**

top - 07:03:39 up 19 days, 16:31,  1 user,  load average: 0.12, 0.05, 0.05
Tasks: 100 total,   1 running,  99 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.1 us,  0.4 sy,  0.0 ni, 95.2 id,  0.0 wa,  0.1 hi,  0.2 si,  0.0 st
MiB Mem :   1578.2 total,    948.9 free,    199.6 used,    429.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1329.9 avail Mem 

That's a 25MB increase in memory over 21 days which does not appear to be significant. Anything else you want me to try @jbleyel?

**Comment by phunkyfish** [comment] 2021-04-10 10:13
With any restart today my device is using: 197MiB which mean the memory leak is definitely gone. @jbleyel I think you can make this the default in OpenWebIf. 

top - 11:12:36 up 21 days, 17:50,  1 user,  load average: 0.21, 0.07, 0.06
Tasks: 100 total,   1 running,  99 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.1 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   1578.2 total,    954.8 free,    197.0 used,    426.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1333.5 avail Mem

**Comment by jbleyel** [comment] 2021-04-11 09:07
This change needs to be tested on all images first.
It seams to be there are no side effects.
But it's untested.

I will make a change on the api to use both.

**Comment by phunkyfish** [comment] 2021-04-11 10:27
Ok, well I run OpenVix so one image down.

**Comment by jbleyel** [comment] 2021-04-11 10:30
you have to add &internal=<something> to the request

**Comment by phunkyfish** [comment] 2021-04-11 10:46
> you have to add `&internal=<something>` to the request

Ok, thanks. And older versions of OpenWebIf will just ignore that hopefully?

**Comment by jbleyel** [comment] 2021-04-11 11:18
yes

**Comment by phunkyfish** [comment] 2021-04-11 12:28
Could we do a version bump? It would mean I can tell users the version they need to be on to get the fix,

**Comment by phunkyfish** [comment] 2021-04-11 12:40
Thanks!

**Closed** 2021-04-11 13:28 UTC
