### ISSUE TITLE
Version is not displayed

### ISSUE THREAD

**Issue by NaseDC** [E2OpenPlugins/e2openplugin-OpenWebif#1509] opened 2022-05-27 20:43 UTC
**Describe the bug**
Version is not displayed under Information if Debug - Display Tracebacks in browser is set to no

**To Reproduce**
Debug - Display Tracebacks in browser set to on , version is displayed
Debug - Display Tracebacks in browser set to off , version is not displayed

**Expected behavior**
Whether Debug - Display Tracebacks in browser is switched on or off, the version must be shown.

**Screenshots**
![off](https://user-images.githubusercontent.com/5048530/170786799-1071d4db-926d-4c92-9a7d-c8b5a534a787.PNG)
![on](https://user-images.githubusercontent.com/5048530/170786802-eded7e0b-cf87-48d4-9ff0-e9f21121e3f9.PNG)

**Image (please complete the following information):**
 - VTI 15

**Desktop (please complete the following information):**
 - Firefox
 - Version 100.0.2 64bit

**Comment by wedebe** [comment] 2022-05-27 23:18
This is by design. Most users don't need to see this information. Perhaps a separate `advanced detail` setting would be more suitable?

**Comment by NaseDC** [comment] 2022-05-28 07:41
That would be an option

**Comment by rdamas** [comment] 2022-05-28 10:48
I don't get the rationale behind the "design"; users frequently want to know, if their upgrade did work. And displaying the version number in OpenWebif doesn't disclose any information not already available from inspecting javascript code. I'm all for not hiding this information behind a configuration option.

**Comment by NaseDC** [comment] 2022-05-28 15:50
I find a direct display more beautiful as well.
But I could also live with it if I had to select "Show version = Yes/No" in the config.

Possibly I can bring here also equal to the request under information the point "reveiver" the spelling mistake to "Receiver" to fix.

**Comment by NaseDC** [comment] 2022-06-04 11:46
THX 4 Fix !
![Unbenannt](https://user-images.githubusercontent.com/5048530/171997548-bf570c56-3f63-4d50-ab7d-fe561b898171.PNG)

**Comment by jbleyel** [comment] 2022-07-05 21:06
can we close this?

**Comment by NaseDC** [comment] 2022-07-17 08:26
Yes, thank you.

**Closed** 2022-07-17 08:42 UTC
Labels: BUG 🐞
