### ISSUE TITLE
Timer scroll region broken

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#515] opened 2016-12-01 19:45 UTC
How to replicate:
Add 5-7 timers from EPG
Select Timer from OWIFs main menu
View the list of timers.
The list exceeds the defined view area and are displayed over the page footers

**Comment by jbleyel** [comment] 2016-12-01 20:24
i will take a look

**Comment by jbleyel** [comment] 2016-12-01 20:28
I have the latest version from dev-1.1 branch and i cannot reproduce the issue.
Please clear the browser cache and use the latest version.

**Comment by jbleyel** [comment] 2016-12-01 20:35
fixed with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/318e55f956b3a35e8719802073a48e548b3831ba

**Closed by jbleyel** 2016-12-01 20:35 UTC

**Comment by Priskvark** [comment] 2016-12-01 20:55
@jbleyel

You are really incredible productive. I wonder how you manage to keep up the fix rate while you at the same time are occupied with development all night long. 

Your customers (or boss) from your daytime work must be very content to have you working for them!

Thank you for your efforts!

**Comment by jbleyel** [comment] 2016-12-01 21:07
I hate bugs ;-)
But this was a typo of mine.
And this is what i'm hating more. ;-)

The improvement of the hole openwebif isn't quite unselfish to include more features in my app. :D
